# Generated by Django 4.1.2 on 2023-11-27 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('build_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('img_url', models.CharField(max_length=100)),
                ('opening_hours', models.CharField(max_length=100)),
                ('build_status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Building',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('birth_date', models.DateField()),
                ('passport_data', models.CharField(max_length=35)),
                ('login', models.CharField(max_length=35, unique=True)),
                ('password', models.CharField(max_length=35, unique=True)),
                ('is_admin', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('permit_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('date_create', models.DateTimeField()),
                ('date_formation', models.DateTimeField(blank=True, null=True)),
                ('passege_date', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='requests_admin_set', to='bmstu_lab_m.user')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bmstu_lab_m.user')),
            ],
            options={
                'db_table': 'Permit',
            },
        ),
        migrations.CreateModel(
            name='Build_Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bmstu_lab_m.building')),
                ('permit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bmstu_lab_m.permit')),
            ],
            options={
                'db_table': 'Build_Permit',
                'unique_together': {('permit', 'build')},
            },
        ),
    ]
