# Generated by Django 4.1.2 on 2023-10-30 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('build_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('img_url', models.CharField(max_length=50)),
                ('opening_hours', models.CharField(max_length=100)),
                ('delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Building',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('birthDate', models.DateField()),
                ('login', models.CharField(max_length=35, unique=True)),
                ('password', models.CharField(max_length=35, unique=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('date_create', models.DateTimeField()),
                ('date_formation', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bmstu_lab_m.user')),
            ],
            options={
                'db_table': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Build_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bmstu_lab_m.building')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bmstu_lab_m.status')),
            ],
            options={
                'db_table': 'Build_Status',
                'unique_together': {('status', 'build')},
            },
        ),
    ]
