# Generated by Django 4.1.2 on 2023-10-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab_m', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='delete',
        ),
        migrations.AddField(
            model_name='building',
            name='build_statuss',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
