# Generated by Django 4.2.4 on 2024-01-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab_m', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='security_decision',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
