# Generated by Django 4.1.2 on 2023-11-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab_m', '0002_remove_building_delete_building_build_statuss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
