# Generated by Django 4.2.5 on 2024-01-21 11:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Корпус', 'verbose_name_plural': 'Корпуса'},
        ),
        migrations.AddField(
            model_name='permit',
            name='security_decision',
            field=models.BooleanField(blank=True, null=True, verbose_name='Решение охраны'),
        ),
        migrations.AlterField(
            model_name='building',
            name='location',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 11, 36, 28, 771614, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moderator', to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
    ]
