# Generated by Django 4.2.5 on 2024-01-22 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_building_options_permit_security_decision_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permit',
            options={'ordering': ('-date_formation',), 'verbose_name': 'Пропуск', 'verbose_name_plural': 'Пропуска'},
        ),
        migrations.AlterField(
            model_name='permit',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 9, 24, 31, 850955, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='passege_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата прохождения'),
        ),
    ]
