# Generated by Django 4.2.4 on 2024-01-22 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_permit_options_alter_permit_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 11, 43, 32, 420058, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
