# Generated by Django 4.2.7 on 2024-01-24 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_permit_date_created_alter_permit_passege_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 13, 39, 59, 202305, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
