# Generated by Django 4.2.7 on 2024-01-26 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_permit_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 26, 3, 22, 11, 664887, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
